apiVersion: v1
kind: Service
metadata:
  name: imageserver
  labels:
    app: imageserver
spec:
  type: ClusterIP
  selector:
    app: imageserver
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
