apiVersion: v1
kind: Service
metadata:
  name: bevy
  labels:
    app: bevy
spec:
  type: ClusterIP
  selector:
    app: bevy
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
