apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver
  labels:
    app: authserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      labels:
        app: authserver
    spec:
      containers:
        - name: authserver
          image: ghcr.io/2143-labs/rots-authserver:server-latest
          command:
            - sh
            - -c
            - "rots-authserver"
          ports:
            - containerPort: &port 8000
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi

          livenessProbe:
            httpGet:
              path: /health
              port: *port
            initialDelaySeconds: 1
            periodSeconds: 1
            failureThreshold: 25

          readinessProbe:
            httpGet:
              path: /health
              port: *port
            initialDelaySeconds: 1
            periodSeconds: 5
            failureThreshold: 3
