apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rots
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - auth.prod.rots.2143.me
      secretName: auth-prod-rots-2143-me-tls
    - hosts:
        - auth.rots.2143.me
      secretName: auth-rots-2143-me-tls
  rules:
    - host: auth.rots.2143.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authserver
                port:
                  number: 80
    - host: auth.prod.rots.2143.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authserver
                port:
                  number: 80
